version: "3"

services:
  bff:
    build:
      context: .
      dockerfile: ./.docker/bff/Dockerfile
    ports: 
      - "3000:3000"
    volumes:
        - .:/code
  nextjs: 
    build: 
      context: .
      dockerfile: ./.docker/web/Dockerfile
    ports: 
      - "3001:3000"